imundongmukjjang/accounts/urls.py
from django.urls import path
#from imundongmukjjang.views import *
from .views import *
from django.conf import settings
from django.conf.urls.static import static

app_name="accounts"

urlpatterns = [
    #path('search/', map_search, name="map_search"),
    path('signup/', signup, name='signup'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('mypage/', mypage, name="mypage"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

imundongmukjjang/imundongmukjjang/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from restaurants.views import init_db, home
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('db/', init_db, name="db"),
    path('', home, name='home'),
    path('accounts/', include('accounts.urls')),
    path('restaurants/', include('restaurants.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

imundongmukjjang/restaurants/urls.py
from os import name
from django.urls import path
from .views import *

app_name="restaurants"

urlpatterns = [
    path('search/<int:sorted_id>/', map_search, name="map_search"),
    path('add_restaurant/', post_restaurant, name="post_restaurant"),
    path('create_restaurant/', create_restaurant, name="create_restaurant"),
    path('<int:restaurant_id>/add_menu_price/', add_menu_price, name="add_menu_price"),
    path('<int:id>/', detail, name='detail'),
    path('update_restaurant/', put_restaurant, name='put_restaurant'),
    path('<int:menu_id>/delete/', menu_delete, name='menu_delete'),
    path('random_menu/', random_menu, name="random_menu"),
    path('random_menu/detail/', random_menu_detail, name="random_menu_detail"),
    path('category/', category, name="category"),
    path('category_detail/<int:category_id>/<int:sorted_id>/', category_detail, name="category_detail"),
    path('lists/<int:sorted>/', rest_lists, name="rest_lists"),
]

imundongmukjjang/restaurants/models.py
from django.db import models
from accounts.models import CustomUser

# Create your models here.
class Big_Category(models.Model):
    name = models.CharField(max_length=45)

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=30)
    big_category = models.ForeignKey(Big_Category, on_delete=models.CASCADE,blank=True, null=True, related_name='big_category')

    def __str__(self):
        return self.name

class Restaurant(models.Model):
    name = models.CharField(max_length=60, null=False)
    phone = models.CharField(max_length=20, null=True)
    rating = models.FloatField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    category = models.ForeignKey('Category', on_delete=models.SET_NULL, blank=True, null=True)
    address = models.CharField(max_length=255)
    owner = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, blank=True, null=True, default=None, related_name='owner')
    max_price = models.IntegerField(default=0)
    min_price = models.IntegerField(default=0)

    def __str__(self):
        return self.name
    
    def short_name(self):
        first_name = self.name.split()[0]
        if len(self.name) >= 7:
            if '이문' in self.name.split()[0] :
                first_name = first_name.replace('이문', ' ')
            if '외대' in self.name:
                first_name = first_name.replace('외대', ' ')
            return self.name.split()[0]
        else:
            return self.name

class Menu_Price(models.Model):
    menu = models.CharField(max_length=45)
    price = models.IntegerField()
    restaurant = models.ForeignKey('Restaurant', on_delete=models.CASCADE, null=False, blank=False, related_name="restaurant")

    def __str__(self):
        return self.menu

imundongmukjjang/restaurants/views.py
from django.shortcuts import render, redirect, get_object_or_404
import pandas as pd
from accounts.models import CustomUser
from .models import Big_Category, Restaurant, Category, Menu_Price
from pathlib import Path
import os
from .form import *
from django.utils import timezone
from imundongmukjjang.settings import KAKAO_APPKEY
import json
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator

BASE_DIR = Path(__file__).resolve().parent.parent
filename = os.path.join(BASE_DIR, 'restaurants', 'restaurants.csv')
# Create your views here.
def home(request):
    return render(request, 'home.html')

def rest_page(request):
    return render(request, 'rest_input.html')

def menu_page(request):
    return render(request, 'menu_input.html')

def init_db(request):
    data = pd.read_csv(filename, encoding = 'utf-8')
    data.head()

    categories = data['카테고리']
    temp = []
    for row in categories:
        if row != 0 and row not in temp:
            temp.append(row)
            new_category = Category()
            new_category.name = row
            new_category.big_category = Big_Category.objects.get(id=1)
            new_category.save()

    for row in data.itertuples():
        status = getattr(row, '영업상태명')
        if status == "영업/정상":
            new_rest = Restaurant()
            new_rest.phone = getattr(row, '전화번호')
            new_rest.address = getattr(row, '도로명주소')
            new_rest.name = getattr(row, '사업장명')
            new_rest.rating = float(getattr(row, '별점'))
            category = getattr(row, '카테고리')
            new_rest.category = Category.objects.get(name=category)
            menus = eval(getattr(row, '메뉴'))
            max_price, min_price = 0, 1000000
            new_rest.save()
            for menu in menus.keys():
                new_menu = Menu_Price()
                new_menu.menu = menu
                if menus[menu] != '':
                    price = int(str(menus[menu]).replace(',',''))
                else: price = 0
                new_menu.price = price
                if max_price < price: max_price = price
                if min_price > price: min_price = price
                new_menu.restaurant = new_rest
                new_menu.save()
            new_rest.max_price, new_rest.min_price = max_price, min_price
            new_rest.save()
    return redirect('home')

def map_search(request, sorted_id):
    keyword = request.GET.get('keyword')
    if keyword != None:
        restaurants = Menu_Price.objects.filter(menu__contains=keyword).prefetch_related("restaurant").order_by('-restaurant__rating')
        if sorted_id == 1:
            restaurants = restaurants.order_by('restaurant__min_price')
        if sorted_id == 2:
            restaurants = restaurants.order_by('-restaurant__rating')
        restaurants_list = list(restaurants)
        data = []
        for rest in restaurants_list:
            if rest.restaurant not in data:
                data.append(rest.restaurant)
        return render(request, 'search.html', {'restaurants': data, 'keyword':keyword, 'KAKAO_APPKEY':KAKAO_APPKEY, 'sorted_id':sorted_id})
    return render(request, 'search.html', {'keyword':keyword, 'sorted_id':sorted_id})

@login_required
def post_restaurant(request):
    categories = Category.objects.all().order_by('name')
    if Restaurant.objects.filter(owner__username=str(request.user)).exists():
        rest = Restaurant.objects.filter(owner__username=str(request.user))
        return render(request, "rest_input.html", {'register': 'exist'})
    return render(request, 'rest_input.html', {'categories':categories})

@login_required
def create_restaurant(request):
    try:
        user = CustomUser.objects.filter(username=str(request.user))
        categories = Category.objects.all().order_by('name')
        if user.exists():
            if user[0].is_assured == True:
                new_restaurant = Restaurant()
                new_restaurant.name = request.POST['name']
                if len(Restaurant.objects.filter(name=request.POST['name'])) != 0:
                    return render(request, "rest_input.html", {'register': 'dup'})
                new_restaurant.phone = request.POST['phone']
                new_restaurant.category = Category.objects.get(id=int(request.POST['category']))
                new_restaurant.owner = user[0]
                new_restaurant.address = request.POST["sample4_roadAddress"] + request.POST["sample4_detailAddress"]
                new_restaurant.save()
                return redirect('restaurants:detail', new_restaurant.id)
        return render(request, "rest_input.html", {'register': 'not_assured', 'categories':categories})
    except Exception as e:
        print(e)
        return render(request, "rest_input.html", {'register': 'wrong'})

@login_required
def put_restaurant(request):
    try:
        restaurants = Restaurant.objects.filter(owner__username=str(request.user))
        ct = Category.objects.all().order_by('name')
        if restaurants.exists():
            restaurant = restaurants[0]
            if request.method == 'POST':
                menus = Menu_Price.objects.filter(restaurant=restaurant)
                restaurant.name = request.POST["title"]
                restaurant.phone = request.POST["phone"]
                restaurant.category = Category.objects.get(id=int(request.POST['category']))
                restaurant.address = request.POST["sample4_roadAddress"] + request.POST["sample4_detailAddress"]
                restaurant.save() 
                return redirect('restaurants:detail', restaurant.id)
            else:
                return render(request, "update.html", {'restaurant':restaurant, "ct": ct})
        return redirect('restaurants:post_restaurant')
    except Exception as e:
        print(e)
        return render(request, "update.html", {'restaurants':restaurants, 'register':'wrong', "ct": ct})

def random_menu(request):
    return render(request, 'random_menu.html')

def random_menu_detail(request):
    #가격이 0원이 아니고 None이 아닌 메뉴가 골라질 때까지 반복
    while True:
        random_selected = Menu_Price.objects.order_by("?").first()
        menu = random_selected.menu
        price = random_selected.price
        restaurant = random_selected.restaurant
        #가격이 0원이 아니고 None이 아니면 반복문 탈출
        if price !=0 and price != None:
            break
    return render(request, 'random_menu_detail.html', {'menu':menu, 'price':price, 'restaurant':restaurant})

# 메뉴 추가 가능하도록 해야 함.
# 메뉴 삭제 가능하도록
@login_required
def add_menu_price(request, restaurant_id):
    restaurant = Restaurant.objects.get(id=restaurant_id)
    menus = Menu_Price.objects.filter(restaurant__id=restaurant.id)
    print(restaurant.owner != None)
    if restaurant.owner != None:
        if request.method == 'POST' and restaurant.owner.username == str(request.user):
            new_menu = Menu_Price()
            new_menu.menu = request.POST["menu"]
            new_menu.restaurant = restaurant
            new_menu.price = request.POST['price']
            new_menu.save()
        return render(request, 'menu_input.html', {'restaurant':restaurant, 'menus':menus})
    return render(request, "update.html", {'restaurant':restaurant, 'register':'wrong'})

def menu_delete(request, menu_id):
    menu = Menu_Price.objects.get(id=menu_id)
    restaurant_id = menu.restaurant.id
    menu.delete()
    return redirect('restaurants:add_menu_price', restaurant_id)

def detail(request, id):
    restaurants = Restaurant.objects.filter(id=id).prefetch_related('owner')
    restaurant = restaurants[0]
    menus = Menu_Price.objects.filter(restaurant__id=id)
    return render(request, 'detail.html', {'restaurant': restaurant, 'menus':menus, 'KAKAO_APPKEY':KAKAO_APPKEY})

def category(request):
    categories = Big_Category.objects.all()
    return render(request, 'category.html', {'categories':categories})

def category_detail(request, category_id, sorted_id):
    '''
    sorted_id 정의
    0 : 정렬 기준 없음
    1 : 최소 가격 기준 정렬
    2 : 평점 기준 정렬
    '''
    restaurants = Restaurant.objects.filter(category__big_category__id=category_id)
    if sorted_id == 1:
        restaurants = restaurants.order_by('min_price')
    elif sorted_id == 2:
        restaurants = restaurants.order_by('-rating')
    paginator = Paginator(restaurants, 10)
    page = request.GET.get('page')
    paginated_restaurants = paginator.get_page(page)
    return render(request, 'category_detail.html', {'restaurants':paginated_restaurants, 'KAKAO_APPKEY':KAKAO_APPKEY, 'category_id':category_id})
    
def rest_lists(request, restaurants, sorted):
    if sorted == 1:
        restaurants_list = restaurants.order_by('min_price')
    elif sorted == 2:
        restaurants_list = restaurants.order_by('rating')
    else: 
        restaurants_list = restaurants
    return render(request, 'rest_lists.html', {'restaurants':restaurants_list,'KAKAO_APPKEY':KAKAO_APPKEY})

imundongmukjjang/restaurants/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block title %}카테고리별 - 부엉아 밥먹자{%endblock%}
{% block link %}
{%endblock%}
{% block content %}
<section class="featured-section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="titie-section wow fadeInDown animated ">
                    <h1>메뉴 선택</h1>
                </div>
            </div>
        </div>
        <div class="row featured isotope">
            <div class="col-md-3 col-sm-6 col-xs-12 cat-3 featured-items isotope-item">
                <div class="product-item">
                    <a href="{% url 'restaurants:category_detail' categories.0.id 0 %}">
                    <img src="{% static 'images/korean.png' %}" class="img-responsive" width="255" height="322" alt="">
                    <div class="product-title">
                            <h3>{{categories.0}}</h3>
                    </div></a>
                </div>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12 cat-2 featured-items isotope-item">
                <div class="product-item">
                    <a href="{% url 'restaurants:category_detail' categories.1.id 0 %}">
                    <img src="{% static 'images/chinese.png'%}" class="img-responsive" width="255" height="322" alt="">
                    <div class="product-title">
                            <h3>{{categories.1}}</h3>
                    </div></a>
                </div>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12 cat-1 featured-items isotope-item">
                <div class="product-item">
                    <a href="{% url 'restaurants:category_detail' categories.2.id 0 %}">
                    <img src="{% static 'images/italian.png'%}" class="img-responsive" width="255" height="322" alt="">
                    <div class="product-title">
                            <h3>{{categories.2}}</h3>
                    </div></a>
                </div>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12 cat-3 featured-items isotope-item">
                <div class="product-item">
                    <a href="{% url 'restaurants:category_detail' categories.3.id 0 %}">
                    <img src="{% static 'images/japanese.png'%}" class="img-responsive" width="255" height="322" alt="">
                    <div class="product-title">
                            <h3>{{categories.3}}</h3>
                    </div></a>
                </div>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12 cat-2 featured-items isotope-item">
                <div class="product-item">
                    <a href="{% url 'restaurants:category_detail' categories.4.id 0 %}">
                    <img src="{% static 'images/coffee.png'%}" class="img-responsive" width="255" height="322" alt="">
                    <div class="product-title">
                            <h3>{{categories.4}}</h3>
                    </div></a>
                </div>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12 cat-3 featured-items isotope-item">
                <div class="product-item">
                    <a href="{% url 'restaurants:category_detail' categories.5.id 0 %}">
                    <img src="{% static 'images/thai.png'%}" class="img-responsive" width="255" height="322" alt="">
                    <div class="product-title">
                            <h3>{{categories.5}}</h3>
                    </div></a>
                </div>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12 cat-1 featured-items isotope-item">
                <div class="product-item">
                    <a href="{% url 'restaurants:category_detail' categories.6.id 0 %}">
                    <img src="{% static 'images/hamburger.png'%}" class="img-responsive" width="255" height="322" alt="">
                    <div class="product-title">
                            <h3>{{categories.6}}</h3>
                    </div></a>
                </div>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12 cat-3 featured-items isotope-item">
                <div class="product-item">
                    <a href="{% url 'restaurants:category_detail' categories.7.id 0 %}">
                    <img src="{% static 'images/chicken.png'%}" class="img-responsive" width="255" height="322" alt="">
                    <div class="product-title">
                            <h3>{{categories.7}}</h3>
                    </div></a>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

imundongmukjjang/restaurants/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}부엉아 밥먹자- 이문동 식당 추천 시스템{%endblock%}
    {% block content %}
    <section class="slider-section">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators slider-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox">
                <div class="item active">
                    <img src="{% static 'images/banner-map.gif' %}" width="1648" height="600" alt="">
                    <div class="carousel-caption">
                        <!--<h2>DRESSES <b>&</b> JEANS</h2>-->
                        <h3>위치별 메뉴로 검색하기</h3>
                        <a href="{% url 'restaurants:map_search' 0 %}">GO</a>
                    </div>
                </div>
                <div class="item">
                    <img src="{% static 'images/banner-menu.gif' %}" width="1648" height="600" alt="">
                    <div class="carousel-caption">
                        <!--<h2>DRESSES <b>&</b> JEANS</h2>-->
                        <h3>카테고리별로 선택하기 <!--<Span>SALE</Span>--></h3>
                        <a href="menu.html">GO</a>
                    </div>
                </div>
                <div class="item ">
                    <img src="{% static 'images/boo.gif' %}" width="1648" height="600" alt="">
                    <div class="carousel-caption">
                        <h2><b>오늘 뭐 먹지?</b></h2>
                        <h3>랜덤 추천</h3>
                        <a href="{% url 'restaurants:random_menu' %}">랜덤GO</a>
                    </div>
                </div>
            </div>

            <!-- Controls -->
            <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                <span class="pe-7s-angle-left glyphicon-chevron-left" aria-hidden="true"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                <span class="pe-7s-angle-right glyphicon-chevron-right" aria-hidden="true"></span>
            </a>
        </div>
    </section>

    <section class="service-section">
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-6 wow fadeInRight animated" data-wow-delay="0.1s">
                    <div class="service-item">
                        <a href="{% url 'restaurants:map_search' 0 %}">
                        <i class="pe-7s-map-2"></i>
                        <h3>위치별 메뉴 검색</h3>
                        <p>정문까지 가기 귀찮은데<br>후문에 맛있는거 없나?</p></a>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6 wow fadeInRight animated" data-wow-delay="0.2s">
                    <a href="{% url 'restaurants:map_search' 0 %}">
                    <div class="service-item">
                        <i class="pe-7s-way"></i>
                        <h3>카테고리별 검색</h3>
                        <p>카테고리별로 모아보기</p>
                    </div></a>
                </div>
                <div class="col-md-3 col-sm-6 wow fadeInRight animated" data-wow-delay="0.3s">
                    <div class="service-item">
                        <a href="{% url 'restaurants:random_menu' %}">
                        <i class="pe-7s-help1"></i>
                        <h3>랜덤 검색</h3>
                        <p>뭐 먹을지 고민될 때<br>부가 추천해주는<br>오늘의 메뉴</p></a>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6 wow fadeInRight animated" data-wow-delay="0.4s">
                    <div class="service-item">
                        <a href="{% url 'restaurants:put_restaurant' %}">
                        <i class="pe-7s-note"></i>
                        <h3> 정보 편집 가능</h3>
                        <p>사업자 로그인을 하면<br>식당의 정보를<br>직접 편집할 수 있습니다.</p></a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% endblock %}

imundongmukjjang/restaurants/templates/random_menu.html
{% extends 'base.html' %}
{% load static %}
{% block title %}랜덤 메뉴 - 부엉아 밥먹자{%endblock%}
{% block link %}
{%endblock%}
{% block content %}
<section class="review-section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="titie-section wow fadeInDown animated ">
                    <h1>랜덤 추천</h1>
                </div>
            </div>
        </div>
        <div class="row">
            <div id="feedback" class="carousel slide feedback" data-ride="feedback">
                <!-- Wrapper for slides -->
                <div class="carousel-inner" role="listbox">
                    <div class="item active">
                        <img src="{% static 'images/random.gif'%}" width="400" height="" alt="">
                        <a href="{% url 'restaurants:random_menu_detail'%}"><img src="{% static 'images/buzzer.png'%}" onmouseover="this.src='{% static 'images/buzzer_active.png'%}'" onmouseout="this.src='{% static 'images/buzzer.png'%}'" width="150" height="100" alt=""></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<br><br><br><br><br><br>
{% endblock %}

imundongmukjjang/restaurants/templates/random_menu_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}랜덤 메뉴 - 부엉아 밥먹자{%endblock%}
{% block link %}
{%endblock%}
{% block content %}
<section class="review-section">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="titie-section wow fadeInDown animated ">
                        <h1>랜덤 추천</h1>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 wow fadeInLeft animated">
                    <div class="left-content">
                        <h1></br></br>오늘은 <span>{{ menu }}</span> <br>어떠세요?</h1>
                        <h2><span><a href="{% url 'restaurants:detail' restaurant.id %}">{{restaurant }}</a></span>에서</br>
                            <span>{{ price }}</span>원에 판매하고 있어요!</h2>
                    </div>
                </div>
                <div class="col-md-6 wow fadeInRight animated">
                        <div class="right-content">
                            <h1></br></h1>
                            <img src="{% static 'images/random_result.gif'%}" width="500px" height="400px" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <br><br><br><br><br><br>
{% endblock %}

imundongmukjjang/restaurants/templates/rest_input.html
{% extends 'base.html' %}
{% load static %}
{% block title %}식당 정보 추가 - 부엉아 밥먹자{%endblock%}
{% block link %}
{%endblock%}
{% block content %}

<section class="news-section">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="titie-section wow fadeInDown animated ">
                    <h1>식당 정보 추가</h1>
                </div>
            </div>
        </div>
        <div class="row" >
            <div class="blog-item">
                <form action="{% url 'restaurants:create_restaurant' %}" method="post" enctype="multipart/form-data">
                {%csrf_token%}
                <h3>
                    <label><i class="pe-7s-ticket"></i> 식당 이름 <input type="text" name="name"></label></br></br>
                    <label><i class="pe-7s-call"></i> 식당 전화번호 <input type="text" name="phone"></label></br></br>
                    <label><i class="pe-7s-menu"></i> 카테고리 
                        <select name="category" >
                            <option value="none">=== 선택 ===</option>
                            {% for category in categories %}
                            <option value="{{category.id}}">{{category}}</option>
                            {% endfor %}    
                        </select>
                    </label></br></br>
                    <label><i class="pe-7s-map-2"></i> 우편 번호 <input type="text" id="sample4_postcode">
                        <button type="button" onclick="sample4_execDaumPostcode()">주소 찾기</button>
                    </label></br>
                    <label><input type="text" name="sample4_roadAddress" id="sample4_roadAddress" placeholder="도로명주소" ></label>
                    <label><input type="text" name="sample4_detailAddress" id="sample4_detailAddress" placeholder="상세주소" ></label>
                        <script src="//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"></script>
                        <script>
                            //본 예제에서는 도로명 주소 표기 방식에 대한 법령에 따라, 내려오는 데이터를 조합하여 올바른 주소를 구성하는 방법을 설명합니다.
                            function sample4_execDaumPostcode() {
                                new daum.Postcode({
                                    oncomplete: function(data) {
                                        // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.
                        
                                        // 도로명 주소의 노출 규칙에 따라 주소를 표시한다.
                                        // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.
                                        var roadAddr = data.roadAddress; // 도로명 주소 변수
                                        var extraRoadAddr = ''; // 참고 항목 변수
                        
                                        // 법정동명이 있을 경우 추가한다. (법정리는 제외)
                                        // 법정동의 경우 마지막 문자가 "동/로/가"로 끝난다.
                                        if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){
                                            extraRoadAddr += data.bname;
                                        }
                                        // 건물명이 있고, 공동주택일 경우 추가한다.
                                        if(data.buildingName !== '' && data.apartment === 'Y'){
                                           extraRoadAddr += (extraRoadAddr !== '' ? ', ' + data.buildingName : data.buildingName);
                                        }
                        
                                        // 우편번호와 주소 정보를 해당 필드에 넣는다.
                                        document.getElementById('sample4_postcode').value = data.zonecode;
                                        document.getElementById("sample4_roadAddress").value = roadAddr;
                                        document.getElementById("sample4_jibunAddress").value = data.jibunAddress;
                                        
                        
                                        var guideTextBox = document.getElementById("guide");
                                        // 사용자가 '선택 안함'을 클릭한 경우, 예상 주소라는 표시를 해준다.
                                        if(data.autoRoadAddress) {
                                            var expRoadAddr = data.autoRoadAddress + extraRoadAddr;
                                            guideTextBox.innerHTML = '(예상 도로명 주소 : ' + expRoadAddr + ')';
                                            guideTextBox.style.display = 'block';
                        
                                        } else if(data.autoJibunAddress) {
                                            var expJibunAddr = data.autoJibunAddress;
                                            guideTextBox.innerHTML = '(예상 지번 주소 : ' + expJibunAddr + ')';
                                            guideTextBox.style.display = 'block';
                                        } else {
                                            guideTextBox.innerHTML = '';
                                            guideTextBox.style.display = 'none';
                                        }
                                    }
                                }).open();
                            }
                        </script>
                    </h3>
                <center><button type="submit" class="btn" style="background-color:#1B2B44; color:#fff; padding: 10px 30px;">저장</button></center>
            </form>
                
                {% if register == 'dup' %}
                <script type="text/javascript">
                alert("중복된 식당명입니다.");
                </script>
                <script type="text/javascript">
                location.href="{% url 'restaurants:post_restaurant'%}";
                </script>
                {% elif register == 'exist' %}
                <script type="text/javascript">
                    alert("이미 등록한 식당이 있는 계정입니다.");
                    </script>
                    <script type="text/javascript">
                    location.href="{% url 'restaurants:put_restaurant'%}";
                    </script>
                {% elif register == 'wrong' %}
                <script type="text/javascript">
                alert("잘못된 양식입니다.");
                </script>
                <script type="text/javascript">
                location.href="{% url 'restaurants:post_restaurant' %}";
                </script>
                {% elif register == 'not_assured' %}
                <script type="text/javascript">
                alert("관리자가 식당 소유 여부를 검토하고 있습니다. 자세한 사항은 관리자에게 문의하세요.");
                </script>
                <script type="text/javascript">
                location.href="{% url 'restaurants:post_restaurant' %}";
                </script>
                {% elif register == 'reg' %}
                <script type="text/javascript">
                alert("정상적으로 등록되었습니다.")
                </script>
                <script type="text/javascript">
                location.href="{% url 'restaurants:add_menu_price' restaurant.id%}";
                </script>
                {% endif %}
            </div>
        </div>
    </div>
</section>
</br></br></br></br></br></br>
{%endblock%}