imundongmukjjang/accounts/urls.py
from django.urls import path
#from imundongmukjjang.views import *
from .views import *
from django.conf import settings
from django.conf.urls.static import static

app_name="accounts"

urlpatterns = [
    #path('search/', map_search, name="map_search"),
    path('signup/', signup, name='signup'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('mypage/', mypage, name="mypage"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

imundongmukjjang/imundongmukjjang/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from restaurants.views import init_db, home
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('db/', init_db, name="db"),
    path('', home, name='home'),
    path('accounts/', include('accounts.urls')),
    path('restaurants/', include('restaurants.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

imundongmukjjang/restaurants/urls.py
from os import name
from django.urls import path
from .views import *

app_name="restaurants"

urlpatterns = [
    path('search/<int:sorted_id>/', map_search, name="map_search"),
    path('add_restaurant/', post_restaurant, name="post_restaurant"),
    path('create_restaurant/', create_restaurant, name="create_restaurant"),
    path('<int:restaurant_id>/add_menu_price/', add_menu_price, name="add_menu_price"),
    path('<int:id>/', detail, name='detail'),
    path('update_restaurant/', put_restaurant, name='put_restaurant'),
    path('<int:menu_id>/delete/', menu_delete, name='menu_delete'),
    path('random_menu/', random_menu, name="random_menu"),
    path('random_menu/detail/', random_menu_detail, name="random_menu_detail"),
    path('category/', category, name="category"),
    path('category_detail/<int:category_id>/<int:sorted_id>/', category_detail, name="category_detail"),
    path('lists/<int:sorted>/', rest_lists, name="rest_lists"),
]

imundongmukjjang/imundongmukjjang/templates/base.html
{%load static%}
<!doctype html>
<html class="no-js" lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>{% block title %}{%endblock%}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="icon" href="{% static 'images/favicon.png' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        {% block link %}{%endblock%}
        <style>
            a{
                color:#555252;
            }
        </style>

        <!--[if lt IE 9]>
            <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
            <script>window.html5 || document.write('<script src="js/vendor/html5shiv.js"><\/script>')</script>
        <![endif]-->
    </head>
    <body>

        <!-- PRELOADER -->
        <div id="preloader">
            <div class="preloader-area">
            	<div class="preloader-box">
            		<div class="preloader"></div>
            	</div>
            </div>
        </div>


        <section class="header-top-section">
            <div class="container">
                <div class="row">
                    <div  class="col-md-6">
                        <div class="header-top-content">
                        </div>
                    </div>
                    <div  class="col-md-6">
                        <div class="header-top-menu">
                            <ul class="nav nav-pills navbar-right">
                                <!--<li><a href="#">My Account</a></li>-->
                                <!--<li><a href="#">Wishlist</a></li>-->
                                <!--<li><a href="#">Cart</a></li>-->
                                <!--<li><a href="#">Checkout</a></li>-->
                                {% if user.is_authenticated %}
                                <li><a href="{% url 'accounts:mypage' %}"><i class="pe-7s-user"></i> 마이페이지</a></li>
                                <li><a href="{% url 'accounts:logout' %}"><i class="pe-7s-unlock"></i> 로그아웃</a></li>
                                {% else %}
                                <li><a href="{% url 'accounts:login' %}"><i class="pe-7s-lock"></i> 로그인</a></li>
                                <li><a href="{% url 'accounts:signup' %}"><i class="pe-7s-add-user"></i> 회원가입</a></li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <header class="header-section">
            <nav class="navbar navbar-default">
                <div class="container">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a href="{% url 'home' %}">
                            <img src="{% static 'images/logo.png' %}" class="img-responsive" width="170" height="85" alt=""></div>
                        </a>
        
                        <!--기존 MART 로고 <a class="navbar-brand" href="#"><b>M</b>art</a>-->
                    </div>

                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav">
                            <li><a href="{% url 'restaurants:map_search' 0 %}">위치별</a></li>
                            <li><a href="{% url 'restaurants:category' %}">카테고리별</a></li>
                            <li><a href="{% url 'restaurants:random_menu' %}">랜덤 추천</a></li>
                            <!--<li><a href="#">Contact Us</a></li>-->
                        </ul>
                        <ul class="nav navbar-nav navbar-right cart-menu">
                        <li><a href="#" class="search-btn"><i class="fa fa-search" aria-hidden="true"></i></a></li>
                        <!--장바구니 메뉴 <li><a href="#"><span> Cart -$0&nbsp;</span> <span class="shoping-cart">0</span></a></li>-->
                    </ul>
                    </div><!-- /.navbar-collapse -->
                </div><!-- /.container -->
            </nav>
        </header>

        <section class="search-section">
            <div class="container">
                <div class="row subscribe-from">
                    <div class="col-md-12">
                        <form class="form-inline col-md-12 wow fadeInDown animated" action="{% url 'restaurants:map_search' 0 %}" method="GET">
                            <div class="form-group">
                                <input type="search" class="form-control" id="search" placeholder="위치별 메뉴 검색" name="keyword">
                                <button class="suscribe-btn" type="submit"><i class="pe-7s-search"></i></button>
                            </div>
                        </form><!-- end /. form -->
                    </div>
                </div><!-- end of/. row -->
            </div><!-- end of /.container -->
        </section><!-- end of /.news letter section -->

        {%block content %}
        {% endblock %}

        <footer class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <p class="center">IMUNDONG <i class="fa fa-love"></i><a href="#">MUKZZANG</a>
                        <p class="center" style="color: #666666;">©캐릭터 Boo는 한국외대 지식출판콘텐츠원의 지적재산입니다.</p>
</p>
                        
                    </div>
                </div>
            </div>
        </footer>

        <!-- JQUERY -->
        <script src="{% static 'js/vendor/jquery-1.11.2.min.js' %}"></script>
        <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
        <script src="{% static 'js/owl.carousel.min.js' %}"></script>
        <script src="{% static 'js/wow.min.js' %}"></script>
        <script src="{% static 'js/custom.js' %}"></script>
    </body>
    {% block bottom %}
    {% endblock %}
</html>