imundongmukjjang/accounts/urls.py
from django.urls import path
#from imundongmukjjang.views import *
from .views import *
from django.conf import settings
from django.conf.urls.static import static

app_name="accounts"

urlpatterns = [
    #path('search/', map_search, name="map_search"),
    path('signup/', signup, name='signup'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('mypage/', mypage, name="mypage"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

imundongmukjjang/imundongmukjjang/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from restaurants.views import init_db, home
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('db/', init_db, name="db"),
    path('', home, name='home'),
    path('accounts/', include('accounts.urls')),
    path('restaurants/', include('restaurants.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

imundongmukjjang/restaurants/urls.py
from os import name
from django.urls import path
from .views import *

app_name="restaurants"

urlpatterns = [
    path('search/<int:sorted_id>/', map_search, name="map_search"),
    path('add_restaurant/', post_restaurant, name="post_restaurant"),
    path('create_restaurant/', create_restaurant, name="create_restaurant"),
    path('<int:restaurant_id>/add_menu_price/', add_menu_price, name="add_menu_price"),
    path('<int:id>/', detail, name='detail'),
    path('update_restaurant/', put_restaurant, name='put_restaurant'),
    path('<int:menu_id>/delete/', menu_delete, name='menu_delete'),
    path('random_menu/', random_menu, name="random_menu"),
    path('random_menu/detail/', random_menu_detail, name="random_menu_detail"),
    path('category/', category, name="category"),
    path('category_detail/<int:category_id>/<int:sorted_id>/', category_detail, name="category_detail"),
    path('lists/<int:sorted>/', rest_lists, name="rest_lists"),
]

imundongmukjjang/accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class CustomUser(User):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    biz_registration = models.ImageField(upload_to="accounts/", blank=True, null=True)
    is_assured = models.BooleanField(default=False)

imundongmukjjang/accounts/views.py
from django.contrib.auth.models import UserManager
from django.shortcuts import render, redirect
from .models import CustomUser
from django.contrib import auth
from django.contrib.auth.decorators import login_required

# Create your views here.


def signup(request):
    if request.method == "POST":
        try:
            if CustomUser.objects.filter(username = request.POST['username']).exists(): # 이미 등록된 회원일 경우
                return render(request, "signup.html", {"validity": 0})
            elif request.POST["password1"] == request.POST["password2"]:    # 회원가입 정상 진행
                user = CustomUser.objects.create_user(
                    username=request.POST["username"], password=request.POST["password1"], biz_registration=request.FILES["uploadedFile"])
                auth.login(request, user)
                return redirect('home')
            else:
                return render(request, "signup.html", {"validity": 1})  # 입력한 비밀번호 두 개가 일치하지 않을 경우
        except Exception as e:
            print(e)
            return render(request, "signup.html", {"filled": 0})
    return render(request, 'signup.html')


def login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(request, username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('home')
        else:
            return render(request, 'signin.html', {"validity": 1})
    else:
        return render(request, 'signin.html')

def logout(request):
    auth.logout(request)
    return redirect('home')

@login_required
def mypage(request):
    return render(request, 'mypage.html')

imundongmukjjang/accounts/templates/mypage.html
{% extends 'base.html' %}
{% load static %}
{% block title %}마이페이지 - 부엉아 밥먹자{%endblock%}
{% block link %}
{%endblock%}
{% block content %}
<section class="review-section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="titie-section wow fadeInDown animated ">
                    <h1>마이페이지</h1>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="service-section">
    <div class="container">
        <div class="row">
            <div class="col-md-3 col-sm-6 wow fadeInRight animated" data-wow-delay="0.1s">
                <div class="service-item">
                </div>
            </div>
            <div class="col-md-3 col-sm-6 wow fadeInRight animated" data-wow-delay="0.2s">
                <div class="service-item">
                    <a href="{% url 'restaurants:post_restaurant' %}">
                        <i class="pe-7s-plus"></i>
                        <h3>식당 정보 추가하기</h3>
                        <p>식당을 추가하여 직접</br>관리할 수 있습니다.</p>
                    </a>
                </div>
            </div>
            <div class="col-md-3 col-sm-6 wow fadeInRight animated" data-wow-delay="0.3s">
                <div class="service-item">
                    <a href="{% url 'restaurants:put_restaurant' %}">
                    <i class="pe-7s-note"></i>
                    <h3>식당 정보 수정하기</h3>
                    <p>식당에 대한 정보를<br>수정할 수 있습니다.</p>
                </a>
                </div>
            </div>
            <div class="col-md-3 col-sm-6 wow fadeInRight animated" data-wow-delay="0.4s">
                <div class="service-item">

                </div>
            </div>
        </div>
    </div>
</section>
<br><br><br><br><br>
{%endblock%}

imundongmukjjang/accounts/templates/signin.html
{% extends 'base.html' %}
{% load static %}
{% block title %}로그인- 부엉아 밥먹자 {%endblock%}
{% block link %}
    <link rel="stylesheet" href="{% static 'css/form-elements.css' %}">
    <link rel="stylesheet" href="{% static 'css/loginstyle.css' %}">
{%endblock%}
{% block content %}

<section class="featured-section">

    <div class="container">
            
        <div class="row">
            <div class="col-sm-12">
                <div class="titie-section wow fadeInDown animated ">
                    <h1>Login</h1>
                </div>
            </div>
        </div>
            
        <div class="row">
            <div class="col-sm-5">
                    
                <div class="form-box">
                    <div class="form-top">
                        <div class="form-top-left">
                            <h3>로그인하여 식당 정보를 직접 관리하세요.</h3>
                            <p>Log in to manage your restaurant information.</p>
                        </div>
                        <div class="form-top-right">
                            <i class="fa fa-key"></i>
                        </div>
                    </div>
                    <div class="form-bottom">
                        <form role="form" action="{% url 'accounts:login' %}" method="post" class="login-form">
                            {% csrf_token %}
                            <div class="form-group">
                                <label class="sr-only" for="form-username">Username</label>
                                <input type="text" name="username" placeholder="Username" class="form-username form-control" id="form-username">
                            </div>
                            <div class="form-group">
                                <label class="sr-only" for="form-password">Password</label>
                                <input type="password" name="password" placeholder="Password" class="form-password form-control" id="form-password">
                            </div>
                            <button type="submit" class="btn">LOGIN</button>
                        </form>
                    </div>
                    <div class="row">
                        <h3>아직 회원이 아니신가요?</h3>
                        <button type="submit" class="btn" onclick = "location.href = '{% url 'accounts:signup' %}' ">회원가입</button>
                        
                    </div>

                </div>
                
            </div>
        </div>
    </div>
</section>
        {% if validity == 1 %}
            <script type="text/javascript">
            alert("아이디 혹은 비밀번호가 맞지 않습니다.");
            </script>
            <script type="text/javascript">
            location.href="{% url 'accounts:login' %}";
            </script>
        {% endif %}

{% endblock %}

imundongmukjjang/accounts/templates/signup.html
{% extends 'base.html' %}
{% load static %}
{% block title %}회원가입- 부엉아 밥먹자 {%endblock%}
{% block link %}
    <link rel="stylesheet" href="{% static 'css/form-elements.css' %}">
    <link rel="stylesheet" href="{% static 'css/loginstyle.css' %}">
{%endblock%}
{% block content %}

<section class="featured-section">
    <div class="container">
            
        <div class="row">
            <div class="col-sm-12">
                <div class="titie-section wow fadeInDown animated ">
                    <h1>회원가입</h1>
                </div>
            </div>
        </div>
            
        <div class="row">
            <div class="col-sm-5">
                    
                <div class="form-box">
                    <div class="form-top">
                        <div class="form-top-left">
                            <h3>회원가입을 위해 정보를 기입해주세요.</h3>
                            <p>Fill in the form below to get instant</p>
                        </div>
                        <div class="form-top-right">
                            <i class="fa fa-pencil"></i>
                        </div>
                    </div>
                    <div class="form-bottom">
                        <form role="form" action="{% url 'accounts:signup' %}" method="post" class="login-form" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                                <label class="sr-only" for="form-username">Username</label>
                                <input type="text" name="username" placeholder="Username..." class="form-username form-control" id="form-username">
                            </div>
                            <div class="form-group">
                                <label class="sr-only" for="form-password">Password</label>
                                <input type="password" name="password1" placeholder="Password..." class="form-password form-control" id="form-password">
                            </div>
                            <div class="form-group">
                                <label class="sr-only" for="form-password">Verify Password</label>
                                <input type="password" name="password2" placeholder="Verify Password..." class="form-password form-control" id="form-password">
                            </div>
                            <div class="form-group">
                                <a><strong>사업자 등록증 첨부</strong></a>
                                    <label class="sr-only" action="http://localhost/upload.php" method="post" enctype="multipart/form-data">Business Registration</label>
                                    <input type="file" name="uploadedFile" placeholder="사업자등록증 첨부">
                            </div>
                            
                            <button type="submit" class="btn">REGISTER</button>
                        </form>
                    </div>
                </div>
                
                
            </div>
        </div>
    </div>
</section>
    {% if validity == 0 %}
    <script type="text/javascript">
    alert("이미 등록된 회원입니다.");
    </script>
    <script type="text/javascript">
    location.href="{% url 'accounts:signup' %}";
    </script>
    {% elif validity == 1 %}
    <script type="text/javascript">
    alert("비밀번호가 일치하지 않습니다.")
    </script>
    <script type="text/javascript">
    location.href="{% url 'accounts:signup' %}";
    </script>
    {% endif %}
    {% if filled == 0 %}
    <script type="text/javascript">
    alert("모든 칸을 채워야 합니다.");
    </script>
    <script type="text/javascript">
    location.href="{% url 'accounts:signup' %}";
    </script>
    {% endif %}
</div>
{% endblock %}